<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DTBN5AF" failures="1" tests="1" name="EdgeTest" time="12.939" errors="0" timestamp="2022-02-12T20:40:35 IST">
  <testcase classname="actitimeTest.CreateNewTaskTestNG" name="createNewTask" time="4.841">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [http://localhost/user/submit_tt.do] but found [http://localhost/login.do]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [http://localhost/user/submit_tt.do] but found [http://localhost/login.do]
at actitimeTest.CreateNewTaskTestNG.createNewTask(CreateNewTaskTestNG.java:112)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createNewTask -->
</testsuite> <!-- EdgeTest -->
